# Generated by Django 2.1 on 2020-10-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=20)),
                ('frequency', models.IntegerField()),
                ('value', models.FloatField()),
                ('value_updated_at', models.DateTimeField()),
            ],
        ),
    ]
