# Generated by Django 2.1 on 2020-10-31 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 14, 51, 28, 926471)),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='value_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
