# Generated by Django 2.1 on 2020-11-01 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201031_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 21, 44, 16, 654739)),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='currency',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='value_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 21, 44, 16, 654739)),
        ),
    ]
